name = "blog-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
VELOG_USERNAME = "njw"

# SYNC_SECRET 은 Cloudflare Dashboard > Workers > Settings > Variables 에서 설정하세요

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "1f3222d0-0343-429c-af67-f771a39b5f2d"
